name: kernel build

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: julian-heng/pkgbuild-action@import-gpg-keys
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    # Uncomment to upload the package as an artifact
    - name: Upload Package Archive
      uses: actions/upload-artifact@v2
      with:
         name: linux-xanmod-aura-archpak
         path: |
          ${{ steps.makepkg.outputs.pkgfile0 }}
          ${{ steps.makepkg.outputs.pkgfile1 }}
